version: '3.8'

services:
  frontend:
    build:
      context: ./FixedAssetsWeb
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  default:
    name: myapp-network
