name: CI Pipeline - Build, Test and Lint

on:
  push:
    branches:
      - main   
  pull_request:
    branches:
      - main   

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x' 

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build the backend
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal

  build-frontend:
    name: Build and Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'  

      - name: Install dependencies
        run: npm install
        working-directory: ./src/FixedAssetsWeb

      - name: Lint the code
        run: npm run lint
        working-directory: ./src/FixedAssetsWeb

      - name: Build the frontend
        run: npm run build
        working-directory: ./src/FixedAssetsWeb
