name: CI Pipeline - Build, Test and Lint

on:
  push:
    branches:
      - main   
  pull_request:
    branches:
      - main   

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' 

      - name: Restore NuGet packages
        run: dotnet restore ./FixedAssets/FixedAssets.sln 

      - name: Build the backend
        run: dotnet build ./FixedAssets/FixedAssets.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ./FixedAssets/FixedAssets.sln --no-build --verbosity normal

  build-frontend:
    name: Build and Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'  

      - name: Install dependencies
        run: npm install
        working-directory: ./FixedAssets/FixedAssetsWeb

      - name: Lint the code
        run: npm run lint
        working-directory: ./FixedAssets/FixedAssetsWeb

      - name: Build the frontend
        run: npm run build
        working-directory: ./FixedAssets/FixedAssetsWeb
        
sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11 (SonarCloud needs it)
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Install .NET dependencies
        run: dotnet restore ./FixedAssets/FixedAssets.sln

      - name: Build the backend
        run: dotnet build ./FixedAssets/FixedAssets.sln --configuration Release

      - name: Run SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"luciana-rocha_FixedAssets" /o:"luciana-rocha" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build ./FixedAssets/FixedAssets.sln
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
